services:
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317" # For OTLP gRPC receiver
      - "55681:55681"

  backend-for-frontend:
    build:
      context: ${SERVICE_PATH:-services}/backend-for-frontend-python
      dockerfile: Dockerfile
    image: backend-for-frontend-python:latest
    ports:
      - "10115:10115"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://api.honeycomb.io
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=tqEvnfLzd2V0fjrjTniymD

  image-picker:
    build:
      context: ${SERVICE_PATH:-services}/image-picker-python
      dockerfile: Dockerfile
    image: image-picker-python:latest
    ports:
      - "10116"
    environment:
      BUCKET_NAME: random-pictures

  meminator:
    build:
      context: ${SERVICE_PATH:-services}/meminator-python
      dockerfile: Dockerfile
    image: meminator-python:latest
    ports:
      - "10117:10117"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://api.honeycomb.io
      - OTEL_EXPORTER_OTLP_HEADERS=x-honeycomb-team=tqEvnfLzd2V0fjrjTniymD

  phrase-picker:
    build:
      context: ${SERVICE_PATH:-services}/phrase-picker-python
      dockerfile: Dockerfile
    image: phrase-picker-python:latest
    ports:
      - "10118"

  web:
    build:
      context: ${SERVICE_PATH:-services}/web
      dockerfile: Dockerfile
    image: web:latest
    # volumes: # uncomment this for faster development on the frontend
    #   - ./services/web/dist:/usr/share/nginx/html # Mount directory containing static files -- only do this for development
    ports:
      - "3000:3000"
    depends_on:
      backend-for-frontend:
        condition: service_started
      image-picker:
        condition: service_started
      meminator:
        condition: service_started
      phrase-picker:
        condition: service_started
